services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: erez
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nbastat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:6
    container_name: redis_db
    ports:
      - "6379:6379"
    networks:
      - app-network

  # app:
  #   build: .
  #   container_name: go_app
  #   depends_on:
  #     - postgres
  #     - redis
  #   environment:
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_USER: erez
  #     DB_PASSWORD: 1234
  #     DB_NAME: nbastat
  #     REDIS_ADDR: redis:6379
  #     REDIS_PASSWORD: ""
  #     REDIS_DB: "0"
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
