services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: erez       # Define PostgreSQL username
      POSTGRES_PASSWORD: 1234   # Define PostgreSQL password
      POSTGRES_DB: nbastat     # Define the database name
    ports:
      - "5432:5432"            # Expose PostgreSQL on port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    container_name: go_app
    depends_on:
      - postgres
    environment:
      DB_HOST: localhost       # Connect to 'localhost' (PostgreSQL container exposed to the host)
      DB_PORT: 5432            # Port to connect to PostgreSQL
      DB_USER: erez            # PostgreSQL username
      DB_PASSWORD: 1234        # PostgreSQL password
      DB_NAME: nbastat         # Database name
    ports:
      - "8080:8080"            # Expose Go app on port 8080
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
